package:
  name: cadracks_party
  version: "0.2.0"

source:
  path: ../cadracks_party

build:
  number: 0
  noarch: python
  script: python setup.py install
  include_recipe: True

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - matplotlib
    - jinja2
    - ccad

about:
  home: https://github.com/osv-team/cadracks_party
  license: GPLv3
  license_file: LICENSE.txt
  summary: Standard CAD parts libraries management